[workspace]
resolver = "2"
members = [
    "crates/sourcetrait_agnostic_macos",
]

[workspace.package]
version = "0.0.0-2"
edition = "2024"
authors = ["SourceTrait <development@sourcetrait.com"]
license = "AGPL-3.0-or-later"
repository = "https://github.com/sourcetrait/sourcetrait_common_mono"
homepage = "https://sourcetrait.com"
categories = []
keywords = ["sourcetrait", "common"]

[workspace.dependencies]
snafu = "0.8"
strum = { version = "0.27", features = ["derive"] }

sourcetrait_agnostic_bridge = { path = "../../sourcetrait_common/crates/sourcetrait_agnostic_bridge" }
sourcetrait_agnostic_unix = { path = "../../sourcetrait_common_mono/unix/crates/sourcetrait_agnostic_unix" }
sourcetrait_stdx = { path = "../../sourcetrait_common/crates/sourcetrait_stdx"  }
sourcetrait_testing = { path = "../../sourcetrait_common/crates/sourcetrait_testing" }
sourcetrait_twostr = { path = "../../sourcetrait_common/crates/sourcetrait_twostr" }
