[package]
name = "sourcetrait_agnostic_windows"
description = "Windows driver for SourceTrait agnostic"
version.workspace    = true
authors.workspace    = true
license.workspace    = true
edition.workspace    = true
repository.workspace = true
homepage.workspace   = true
categories.workspace = true
keywords.workspace   = true

[dependencies]
snafu.workspace = true
sourcetrait_twostr.workspace = true
sourcetrait_agnostic_bridge = { workspace = true, optional = true }
strum.workspace = true
widestring.workspace = true
windows-sys.workspace = true

[dev-dependencies]
sourcetrait_testing.workspace = true

[features]
default = ["agnostic"]
agnostic = ["sourcetrait_agnostic_bridge"]
