[package]
name = "sourcetrait_agnostic_unix"
description = "Unix driver for SourceTrait Agnostic"
version.workspace    = true
authors.workspace    = true
license.workspace    = true
edition.workspace    = true
repository.workspace = true
homepage.workspace   = true
categories.workspace = true
keywords.workspace   = true

[dependencies]
const_format.workspace = true
snafu.workspace = true
sourcetrait_twostr.workspace = true
sourcetrait_agnostic_bridge = { workspace = true, optional = true }

[target.'cfg(target_family = "unix")'.dependencies]
libc.workspace = true

[dev-dependencies]
sourcetrait_testing.workspace = true

[features]
default = ["agnostic"]
agnostic = ["sourcetrait_agnostic_bridge"]
